CREATE TABLE IF NOT EXISTS wallets (
	id UUID PRIMARY KEY, 
	balance BIGINT NOT NULL DEFAULT 0, 
	created_at TIMESTAMP NOT NULL, 
	updated_at TIMESTAMP NOT NULL, 
	version INTEGER NOT NULL DEFAULT 1
);
